name: API Testing

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout Code
        uses: actions/setup-java@v3

        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean test -U -Ptests
      - name: archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: sparkHtml
          path: ./extent-test-output/*.html

